language: php
php:
  - 5.6
install:
  - composer self-update
  - composer install --no-interaction
  - composer require satooshi/php-coveralls:* --dev
script:
  - mkdir build
  - mkdir build/coverage
  - php vendor/bin/phpunit
notifications:
  email:
    recipients:
      - goodjun@163.com
    on_success: change