language: php
php:
  - 5.6
  - 7.0
  - 7.3
install:
  - composer self-update
  - composer install --no-interaction
script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit
after_success:
  - travis_retry php vendor/bin/php-coveralls -v